### ISSUE TITLE
Batch action: determine

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#859]
Batch actions will allow OTF staff to apply the same action to multiple submissions at the same time via the listing table. 

**Acceptance criteria**

- [x] When at least one submission row is selected using the checkbox, determination status updates available in update status batch action. 
- [x] Batch determination changes can only be applied to submissions that can have the same determinations applied to them. The determination options will be disabled if selected submissions can't all have that determination action applied.
- [x] Clicking on a determination status update will take the user to the Add determination form but with extra context about the submissions selected (number of submissions and expand link to see submission titles) to clarify that this is a batch action. Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781109
- [x] Save draft is not available on batch determinations
- [x] On batch action submit, a confirmation modal appears (Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781108).
- [x] On batch action confirmation, user is taken back to submission table from where the batch action was performed. Batch selections are unselected and message displayed to user confirming action (design of message as per https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971429 but no undo!)
* If error when processing batch updating display message to user (same design as per action confirmation at top of screen)
    - [x] If error in processing form - show on determination page
- [x] If submission is determined while batch determination is ongoing, successfully determine all applications where possible and inform batch determiner about the submissions we could not process. Use an error message displaying on originating table.
- [x] Batch actions available on all submission tables on All Submissions page, Submissions by Round page and Submission by Status page (not submission summary blocks on dashboard or submission overview page)
- [x] Users will have the same permissions to perform changes as they do currently
- [x] The same determination message will be sent to all selected submissions.
- [x] Email notifications are unaffected: Applicants will each receive emails as if an action had been taken on their submission only
- [x] Activity feed entries are unaffected: Submissions will have an activity added, it will not be tracked as a batch action 
- [x] Slack notifications updated: only one notification is sent to handle batch message e.g. `“<user> has done <action> to: <submission1><submission2><submission3>”`

Design (batch actions on submission): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971996
Design (add determination form): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781109
Design (confirmation modal): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781108
 

**QA criteria**
Dev:

- [ ] checked feature meets acceptance criteria/conforms exactly to the specification.
- [ ] provided good unit test coverage (if this is non-trivial behaviour).
- [ ] checked all tests for the project pass with this feature enabled.
- [ ] checked code conforms to the project coding standards.
- [ ] had code reviewed by another developer and resolved any issues raised.
- [ ] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [ ] checked that this feature works on the server/s I am deploying it to.

QA:

 * [ ] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [ ] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
FE work here - https://github.com/OpenTechFund/opentech.fund/pull/1023

**Comment by todd-dembrey** [comment]
@gibbsmaya I have deployed this to develop. This includes all @chris-lawton changes from #1023

**Comment by gibbsmaya** [comment]
Testing on https://dev-apply.opentech.fund/apply/submissions/all/

 - selecting 'Demo project' and 'Testing a project as AC member' that are both in internal review state - only determination option I get is 'invite for proposal'. Should I not also have the Dismiss option available?

- tried testing batch dismissing another two submissions and got a 500 error (https://dev-apply.opentech.fund/apply/submissions/batch-determine/?action=rejected&submissions=19,20). Both applications in 'ready for discussion' status.

**Comment by todd-dembrey** [comment]
@gibbsmaya I'm pushing a fix for the 500 error now. You were both a staff member and a super user which was confusing the query.

No, the current workflow does not allow you to dismiss while a internal review is open, only `close review` and `invite to proposal`

**Comment by gibbsmaya** [comment]
Hi @todd-dembrey 

I'm afraid I am still getting a 500 error on https://dev-apply.opentech.fund/apply/submissions/batch-determine/?action=rejected&submissions=10,21.

Thanks,
Maya

**Comment by todd-dembrey** [comment]
Sorry maya,  as per #1009 the code did update on dev. sorry about that.

This is now live.

**Comment by gibbsmaya** [comment]
LGTM. Please deploy to test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work is adding a batch action for determining submissions. You can access this on the all submissions page at https://test-apply.opentech.fund/apply/submissions/all/. Note the determinations do not have a separate button but are accessed as options in the update status batch action.

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are functional and visible. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey ready for live deployment.
